language: minimal
services:
  - docker
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - cat *.Dockerfile > Dockerfile
  - docker build . -t orestisfl/env:latest
  - docker push orestisfl/env:latest
