language: minimal
services:
  - docker
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - cat base.Dockerfile > Dockerfile
  - docker build . -t orestisfl/env:dev
  - docker push orestisfl/env:dev
