name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      shell: bash
      run: ./create_Dockerfile.py && docker build . --file Dockerfile --tag my-image-name:$(date +%s)
